/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mo.kairosanalysisplugin;

import facialAnalysisCore.FacialAnalyser;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;
import mo.organization.ProjectOrganization;

public class KairosFacialConfigDialog extends javax.swing.JDialog {

    boolean accepted;
    FacialAnalyser analyzer;
    boolean configurationFieldClicked;
    boolean keyFieldClicked;

    public KairosFacialConfigDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.configurationFieldClicked = false;
        this.keyFieldClicked = false;
        this.analyzer = null;
        this.setLocationRelativeTo(null);
        initComponents();
        this.setLocationRelativeTo(null);
        

    }

    public KairosFacialConfigDialog() {
        super(null, "configuracion de analisis", ModalityType.APPLICATION_MODAL);
        this.configurationFieldClicked = false;
        this.keyFieldClicked = false;
        this.setLocationRelativeTo(null);
        initComponents();
        this.analyzer=null;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    KairosFacialConfigDialog(ProjectOrganization organization) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public FacialAnalyser getAnalyzer(){return this.analyzer;};

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configurationField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        keyField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        getFreeKey = new javax.swing.JLabel();
        app_idField = new javax.swing.JTextField();
        app_id_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración plugin microsoft cognitive");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        configurationField.setText("Nombre Configuración");
        configurationField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configurationFieldMouseClicked(evt);
            }
        });
        configurationField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                configurationFieldKeyPressed(evt);
            }
        });

        jLabel1.setText("Nombre de Configuración");

        acceptButton.setText("Aceptar");
        acceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptButtonMouseClicked(evt);
            }
        });
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Kairos");

        keyField.setText("app key");
        keyField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keyFieldMouseClicked(evt);
            }
        });
        keyField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyFieldKeyPressed(evt);
            }
        });

        jLabel3.setText("app_key");

        getFreeKey.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getFreeKey.setForeground(new java.awt.Color(0, 0, 204));
        getFreeKey.setText("Obtener una suscripción gratuita ");
        getFreeKey.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getFreeKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getFreeKeyMouseClicked(evt);
            }
        });

        app_idField.setText("app id");
        app_idField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                app_idFieldKeyPressed(evt);
            }
        });

        app_id_label.setText("app_id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(app_idField)
                    .addComponent(configurationField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(keyField)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(acceptButton)
                        .addComponent(getFreeKey)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(app_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(configurationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(app_idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(app_id_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(getFreeKey)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(acceptButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptButtonMouseClicked
        
        if(this.configurationField.getText().equals("")||this.configurationField.getText()==null ||
           this.keyField.getText().equals("") || this.keyField.getText()==null){
            JOptionPane.showMessageDialog(null,"Porfavor complete todos los campos");
        }
        else
        {
            this.accepted = true;
            this.analyzer = new KairosAnalyser("https://api.kairos.com/v2/media",
                                                           this.app_idField.getText(),
                                                           this.keyField.getText());        
            this.dispose();
        }
    }//GEN-LAST:event_acceptButtonMouseClicked

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked

        this.dispose();
       
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void configurationFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurationFieldMouseClicked
      if(this.configurationField.getText().equals("Nombre Configuración")){ 
          this.configurationField.setText(null); 
      }
      
    }//GEN-LAST:event_configurationFieldMouseClicked

    private void keyFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyFieldMouseClicked
      if(this.keyField.getText().equals("key")){ 
          this.keyField.setText(null); 
      }
    }//GEN-LAST:event_keyFieldMouseClicked

    private void getFreeKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getFreeKeyMouseClicked
        try{
            Desktop.getDesktop().browse(new URI("https://developer.kairos.com/signup?plan_ids[]=2357355666521"));
        }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Porfavor dirijase a https://developer.kairos.com/signup?plan_ids[]=2357355666521");
        }


    }//GEN-LAST:event_getFreeKeyMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        char enter = '\n';
            if(evt.getKeyChar()==enter){
                        if(this.configurationField.getText().equals("")||this.configurationField.getText()==null ||
               this.keyField.getText().equals("") || this.keyField.getText()==null){
                JOptionPane.showMessageDialog(null,"Porfavor complete todos los campos");
            }
            else
            {
                this.accepted = true;
                this.analyzer = new KairosAnalyser("https://api.kairos.com/v2/media",
                                                               this.app_idField.getText(),
                                                               this.keyField.getText());        
                this.dispose();
            }
        }
    }//GEN-LAST:event_formKeyPressed

    private void configurationFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_configurationFieldKeyPressed
        char enter = '\n';
            if(evt.getKeyChar()==enter){
                        if(this.configurationField.getText().equals("")||this.configurationField.getText()==null ||
               this.keyField.getText().equals("") || this.keyField.getText()==null){
                JOptionPane.showMessageDialog(null,"Porfavor complete todos los campos");
            }
            else
            {
                this.accepted = true;
                this.analyzer = new KairosAnalyser("https://api.kairos.com/v2/media",
                                                               this.app_idField.getText(),
                                                               this.keyField.getText());        
                this.dispose();
            }
        }
    }//GEN-LAST:event_configurationFieldKeyPressed

    private void app_idFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_app_idFieldKeyPressed
        char enter = '\n';
            if(evt.getKeyChar()==enter){
                        if(this.configurationField.getText().equals("")||this.configurationField.getText()==null ||
               this.keyField.getText().equals("") || this.keyField.getText()==null){
                JOptionPane.showMessageDialog(null,"Porfavor complete todos los campos");
            }
            else
            {
                this.accepted = true;
                this.analyzer = new KairosAnalyser("https://api.kairos.com/v2/media",
                                                               this.app_idField.getText(),
                                                               this.keyField.getText());        
                this.dispose();
            }
        }
    }//GEN-LAST:event_app_idFieldKeyPressed

    private void keyFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyFieldKeyPressed
        char enter = '\n';
            if(evt.getKeyChar()==enter){
                        if(this.configurationField.getText().equals("")||this.configurationField.getText()==null ||
               this.keyField.getText().equals("") || this.keyField.getText()==null){
                JOptionPane.showMessageDialog(null,"Porfavor complete todos los campos");
            }
            else
            {
                this.accepted = true;
                this.analyzer = new KairosAnalyser("https://api.kairos.com/v2/media",
                                                               this.app_idField.getText(),
                                                               this.keyField.getText());        
                this.dispose();
            }
        }
    }//GEN-LAST:event_keyFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KairosFacialConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KairosFacialConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KairosFacialConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KairosFacialConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KairosFacialConfigDialog dialog = new KairosFacialConfigDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JTextField app_idField;
    private javax.swing.JLabel app_id_label;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField configurationField;
    private javax.swing.JLabel getFreeKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField keyField;
    // End of variables declaration//GEN-END:variables

    public boolean showDialog() {
        return this.accepted;

    }

    public String getConfigurationName() {
        return this.configurationField.getText();
    }
}
